name: CI
on:
    push:
        branches: 
            - dev

jobs: 
    checkstyles:
        runs-on: ubuntu-latest
        steps:
            - name: Run checkstyles on code base
              run: java -jar checkstyle-8.33-all.jar -c checkstyles.xml  .
