name: CI
on:
    push:
        branches: 
            - dev

jobs: 
    checkstyles:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up jdk 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8
            
                  
            - name: Run Checkstyles for Java Code
              run: java -jar checkstyle-8.33-all.jar -c checkstyles.xml -o checkstyles_audit .
              
            - name: Commit new checkstyles report
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                git config --global user.name 'Debasis Dwivedy'
                git config --global user.email 'dwivedy.debasis@gmail.com'
                git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/debasisdwivedy/TeamFlash.git
                git add checkstyles_audit
                git commit -am "Add Checkstyles report"
                git push
              

            
            
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up jdk 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8
            - name: Build with maven
              run: mvn -f pom.xml clean compile
            - name: Package with maven
              run: mvn -B package -f pom.xml
            
