name: CI
on:
    push:
        branches: 
            - dev

jobs: 
    checkstyles:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up jdk 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8
            - name: Run Checkstyles for Java Code
              run: java -jar checkstyle-8.33-all.jar -c checkstyles.xml -o checkstyles_audit .
    build:
        steps:
            - uses: actions/checkout@v2
            - name: Set up jdk 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8
            - name: Build with maven
              run: mvn -f pom.xml clean compile
            - name: Package with maven
              run: mvn -B package -f pom.xml
            
